function data = importFile_static(fileToRead1, variableName)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 06-Feb-2014 11:39:24

% identifico i vari dati tra di essi,che sono intervallati dalla virgola
DELIMITER = ',';
%le righe che saltiamo perchè non presentano i dati
HEADERLINES = 7;

% Import the file
newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.
%vars = fieldnames(newData1);
%for i = 1:length(vars)
%    assignin('base', vars{i}, newData1.(vars{i}));
%end
assignin('base', variableName, newData1.data);

% Return data
data = newData1.data;

